scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    static_configs:
      - targets: ["otel-collector:8889"]
      # - targets: ["otel-collector:8822"]

# Data retention configuration
# storage:
#   retention: "30d" # Retain data for 30 days